site_name: Showroom Lab Authoring Essentials
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Writing Your Lab: modules/module-01-writing-your-lab.md
  - Module 2 - Antora: modules/module-02-antora.md
  - Module 3 - Tabs: modules/module-03-tabs.md
plugins:
- techdocs-core
